name: compilar iso debian lite
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: instalar dependencias de compilacion 
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build debootstrap wget debian-archive-keyring

      - name: actualizar scripts de debootstrap para trixie
        run: |
          sudo ln -sf sid /usr/share/debootstrap/scripts/trixie || true

      - name: descargar e integrar peazip
        run: |
          mkdir -p config/packages.chroot
          wget --nno-check-certificate https://github.com/peazip/PeaZip/releases/download/11.3.0/peazip_11.3.0.LINUX.GTK2-1_amd64.deb -O config/packages.chroot/peazip.deb || true

      - name: configurar y generar la imagen iso
        run: |
          sudo lb clean --purge
          sudo lb config \
            --architectures amd64 \
            --distribution trixie \
            --binary-images iso-hybrid \
            --archive-areas "main contrib non-free non-free-firmware" \
            --keyring-packages debian-archive-keyring \
            --mode debian \
            --security false \
            --updates false \
            --mirror-bootstrap "http://deb.debian.org/debian/" \
            --mirror-chroot "http://deb.debian.org/debian/" \
            --mirror-binary "http://deb.debian.org/debian/" 
          sudo lb build
          sudo chmod 644 *.iso
          
      - name: subir la iso a github artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mat-os-lite-amd64.iso
          path: "*.iso"
